version: 2
jobs:
  build:
    docker:
      - image: node

    environment:
      TEST_REPORTS: /tmp/test-reports

    working_directory: ~/frontend

    steps:
      - checkout

      - run:
          command: |
            npm install
            npm run build

      # Save artifacts
      - store_artifacts:
      
          path: frontend/docker/dist/*
          destination: dist/

  

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/
