version: 2
jobs:
  build-backend:
      docker:
        - image: openjdk:8-jdk

      environment:
        TEST_REPORTS: /tmp/test-reports

      steps:
        - checkout

        - run:
            command: ./gradlew build

            working_directory: backend

        # Save artifacts
        - store_artifacts:

            path: backend/build/libs/
            destination: dist/backend
            
  build-frontend:
    docker:
      - image: node

    environment:
      TEST_REPORTS: /tmp/test-reports

    steps:
      - checkout

      - run:
          command: |
            npm install
            npm run build
            
          working_directory: frontend

      # Save artifacts
      - store_artifacts:
      
          path: frontend/docker/dist/
          destination: dist/
          
    

  

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-frontend:
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/
      - build-backend:
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/
